<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <AssemblyName>WebKit.ExampleApp</AssemblyName>
    <RootNamespace>WebKit.ExampleApp</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\WebKit.Web\WebKit.Web.csproj" />
    <ProjectReference Include="..\..\src\WebKit.UI\WebKit.UI.csproj" />
    <ProjectReference Include="..\..\src\WebKit.Design\WebKit.Design.csproj" />
  </ItemGroup>
</Project>
