<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Juloc.WebKit.Web" Version="0.2.0" />
    <PackageReference Include="Juloc.WebKit.UI" Version="0.2.0" />
    <PackageReference Include="Juloc.WebKit.Design" Version="0.2.0" />
  </ItemGroup>
</Project>
